  # Authenticate with docker hub
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$DOCKER_USERNAME --password=$$DOCKER_PAT']
   secretEnv: ['DOCKER_USERNAME', 'DOCKER_PAT']

  # Push to docker hub and run
 - name: "gcr.io/cloud-builders/docker"
   entrypoint: 'bash'
   args: ['-c', 'docker run $$DOCKER_USERNAME/superfan-bot:latest']
   secretEnv: ['DOCKER_USERNAME']

    # For Unix Socket connections
  - id: "migrate-socket"
    name: "${_IMAGE_NAME}-proxy"
    dir: sql-proxy
    env:
      - "DATABASE_NAME=${_DATABASE_NAME}"
      - "DATABASE_USER=${_DATABASE_USER}"
      - "INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}"
      - "DATABASE_TYPE=${_DATABASE_TYPE}"
    secretEnv:
      - DATABASE_PASS
      - OPENAI_TOKEN
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        /cloudsql/cloud_sql_proxy -instances=${_INSTANCE_CONNECTION_NAME} -dir=/cloudsql & sleep 2;
        if [ $_DATABASE_TYPE = 'mssql' ]; then echo "MSSQL doesn't support Unix Sockets. Skippng."; exit 0; fi;
        python migrate.py # for example.

options:
  dynamic_substitutions: true

substitutions:
  _DATABASE_USER: new-user
  _DATABASE_NAME: database1
  _INSTANCE_CONNECTION_NAME: ${PROJECT_ID}:us-central1:civ6-wikia
  _DATABASE_PORT: '5432'
  _DATABASE_TYPE: postgres
  _DATABASE_PASSWORD_KEY: database_password
  _OPENAI_TOKEN_KEY: openai_token
  _API_TOKEN_KEY: api_token
  _DOCKER_USERNAME_KEY: docker_username
  _DOCKER_PAT_KEY: docker_pat
  _IMAGE_NAME: gcr.io/${PROJECT_ID}/sample-sql-proxy

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_DATABASE_PASSWORD_KEY}/versions/latest
      env: DATABASE_PASS
    - versionName: projects/$PROJECT_ID/secrets/${_OPENAI_TOKEN_KEY}/versions/latest
      env: OPENAI_TOKEN
    - versionName: projects/$PROJECT_ID/secrets/${_API_TOKEN_KEY}/versions/latest
      env: API_TOKEN
    - versionName: projects/$PROJECT_ID/secrets/${_DOCKER_USERNAME_KEY}/versions/latest
      env: DOCKER_USERNAME
    - versionName: projects/$PROJECT_ID/secrets/${_DOCKER_PAT_KEY}/versions/latest
      env: DOCKER_PAT
images:
  - gcr.io/${PROJECT_ID}/github.com/Gordon-BP/superfan-bot