name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
